kind: Service
apiVersion: v1
metadata:
  name: dhstore
  labels:
    app: dhstore
spec:
  ports:
    - name: http
      port: 40080
      targetPort: http
  selector:
    app: dhstore
  type: ClusterIP
  clusterIP: None
