name: Go Check Setup
description: Set up the environment for go check
runs:
  using: "composite"
  steps:
    - name: Enable CGO
      shell: bash
      run: |
        echo 'CGO_ENABLED=1' >> $GITHUB_ENV
    - name: Install FoundationDB Client C bindings on Linux
      env:
        FDB_VERSION: '7.1.33'
        FDB_CLIENTS_DEB_SHA256_SUM: 'd73002bc796de7ce0158f1eb64fab1f8e90bada2edd90599d9b40754220150af'
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        wget "https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_amd64.deb"
        echo "${FDB_CLIENTS_DEB_SHA256_SUM}  foundationdb-clients_${FDB_VERSION}-1_amd64.deb" | sha256sum --check
        sudo dpkg --force-all -i foundationdb-clients_${FDB_VERSION}-1_amd64.deb